### ISSUE TITLE
features for production

### ISSUE THREAD

**Issue by fredzannarbor** [ml-tooling/opyrator#15]
This looks great and my first thought was, wow, this looks like a great alternative to Flask!  but how would i implement things like  authentication & connections to a database -- things that would likely be needed for any real "production" implementation?

**Comment by raethlein** [comment]
Thanks for the nice feedback! 
In the current alpha version, you could add a token field to the Input object for passing an authentication token. 
With regards to databases, you can connect to them in your opyrator functions. Since in the current version only a single function is allowed, you would need two files for a storing / loading example. The following example illustrates how this could look like:

<details>
<summary>Opyrator to save data</summary>

`app_save.py`

```python

# app_save.py
from pydantic import BaseModel
import time
import sqlite3

db_name = 'example.db'
try:
    con = sqlite3.connect(db_name)
    cur = con.cursor()
    cur.execute('CREATE TABLE messages (timestamp text, message text)')
    con.commit()
    con.close
except Exception:
    pass


class Input(BaseModel):
    message: str
    token: str


class Output(BaseModel):
    status: str


def save(input: Input) -> Output:
    if input.token != 'foo':
        return Output(status="Not authenticated")

    con = sqlite3.connect(db_name)
    cur = con.cursor()

    cur.execute(f"INSERT INTO messages VALUES ('{int(time.time())}', '{input.message}')")
    con.commit()
    con.close()

    return Output(status="saved")
```

</details>

<details>
<summary>Opyrator to load data</summary>

`app_load.py`

```python
from pydantic import BaseModel
from typing import List
import sqlite3


class Input(BaseModel):
    pass


class Output(BaseModel):
    messages: List[str]


def load(input: Input) -> Output:
    con = sqlite3.connect('example.db')
    cur = con.cursor()
    messages = []
    for row in cur.execute('SELECT * FROM messages ORDER BY timestamp'):
        messages.append(row[1])

    return Output(messages=messages)
```

</details>

Start them via:
```
opyrator launch-ui app_save:save --port 8080
opyrator launch-ui app_load:load --port 8081
```

**Comment by sushil79g** [comment]
Thank you again for awesome work, it will be really great if _opyrator_ has in-built support of SQL alchemy or any ORM.
